#!/usr/bin/env bash
# Fix Nginx to listen on port 80

# Check if Nginx is installed, if not install it
apt-get -y update
apt-get -y install nginx

# Remove default Nginx configuration
rm /etc/nginx/sites-enabled/default
# Create a symbolic link to the default configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart 